### ISSUE TITLE
I Can't Swap Panther coin. Can your help me ? plaese

### ISSUE THREAD

**Issue by nikmail** [TechRate/Smart-Contract-Audits#3]
![image](https://user-images.githubusercontent.com/83523574/116799452-a677b480-ab23-11eb-8ea1-fec1a5227cf8.png)

I saw comment after click swap panther coin and bnb , pancake , Busd 

"The transaction cannot succeed due to error: PancakeRouter: INSUFFICIENT_OUTPUT_AMOUNT. This is probably an issue with one of the tokens you are swapping."

thx

**Comment by MrCrambo** [comment]
Contact the Pantherswap team!
