### ISSUE TITLE
Domain is down

### ISSUE THREAD

**Issue by criativocyber** [TechRate/Smart-Contract-Audits#5]
https://pumaswap.fi   is down could you please help me? I know that you have been with the contact of the platform

**Comment by criativocyber** [comment]
Do you have any solution for this?

**Comment by TechRate** [comment]
No, we are not the team members of the PumaSwap, so contact them please.

By the way, do not invest in the projects, which are not even verified their code!

**Comment by criativocyber** [comment]
Thanks for you information, how can I contact them? I know that you are not on PumaSwap team members. But you have made a Full Smart Contract Security Audit? Could you please give me some information about them?

**Comment by criativocyber** [comment]
Really strange saying that "By the way, do not invest in the projects, which are not even verified their code!" when you have on Issues Checking Status List Passed on all Parameters, really helpfull your help...

**Comment by TechRate** [comment]
By the way, there is no issues in that part of the code that we audited.

The issue on the LP tokens, which are not audited and PumaSwap team not verified code of these pairs.

So we are not auditing the project, its members, all the contracts of the project, which are even not provided for us. We are just auditing the contracts which are sent us by team members. In this case these were two contracts - Token and MasterChef, which are free of any high severity issues and passed all the checking list.

**Comment by criativocyber** [comment]
Could you please send to me the email of the company or the phone number?
